# Generated by Django 4.0.4 on 2022-05-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_status_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile',
            field=models.IntegerField(default=1),
        ),
    ]
