# Generated by Django 4.0.4 on 2022-05-18 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='status_id',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.status'),
        ),
    ]
