# Generated by Django 4.0.4 on 2022-05-14 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_account_customer_id_alter_account_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='card_number',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='bank',
            name='clabe',
            field=models.CharField(max_length=18),
        ),
    ]
