# Generated by Django 4.0.4 on 2022-06-04 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_account_renovable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='expiration_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
