# Generated by Django 4.0.4 on 2022-06-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_sale_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='expiration_date',
            field=models.DateTimeField(),
        ),
    ]
