# Generated by Django 4.0.4 on 2022-06-09 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_sale_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='former_sale',
            field=models.IntegerField(default=None),
        ),
    ]
