# Generated by Django 4.0.4 on 2022-06-15 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_customer_email_alter_customer_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='reward_used',
            field=models.BooleanField(default=False),
        ),
    ]
