# Generated by Django 4.0.4 on 2022-06-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_customer_reward_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='former_sale',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
