# Generated by Django 4.0.4 on 2022-06-16 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_sale_former_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cupon', models.CharField(max_length=8)),
                ('expiration_time', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('redeption_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('paid', models.BooleanField(default=False)),
                ('sold', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.account')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.customer')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.status')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.business')),
            ],
        ),
    ]
