# Generated by Django 4.0.4 on 2022-06-23 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_cupon_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupon',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.sale'),
        ),
        migrations.AlterField(
            model_name='cupon',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.account'),
        ),
    ]
