# Generated by Django 4.0.4 on 2022-06-23 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_cupon_account_selected_alter_cupon_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cupon',
            old_name='redeption_date',
            new_name='redemption_date',
        ),
    ]
